'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Skeleton} from '@/components/ui/skeleton';
import {budgets,colors,designs,money,services} from '@/lib/catalog';
type Inquiry={id:string;reference:string;service:string;design:string;material:string;color:string;quote_amount:number|null;budget:string;name:string;contact_type:string;contact:string;watch_model:string;notes:string;status:string;created_at:string};
export default function AdminInquiries(){
  const [items,setItems]=useState<Inquiry[]>([]);const [filter,setFilter]=useState('all');const [counts,setCounts]=useState({total:0,pending:0});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [more,setMore]=useState(false);const [updating,setUpdating]=useState('');const sequence=useRef(0);
  const load=useCallback(async(offset=0)=>{const seq=++sequence.current;setLoading(true);setError('');try{const response=await fetch(`/api/admin/inquiries?status=${filter}&offset=${offset}`,{cache:'no-store'});const data=await response.json() as {error?:string;items:Inquiry[];hasMore:boolean;counts:{total:number;pending:number}};if(!response.ok)throw new Error(data.error);if(seq!==sequence.current)return;setItems(previous=>offset?[...previous,...data.items]:data.items);setMore(data.hasMore);setCounts(data.counts);}catch(err){if(seq===sequence.current)setError(err instanceof Error?err.message:'讀取失敗，請重試。');}finally{if(seq===sequence.current)setLoading(false);}},[filter]);
  useEffect(()=>{setItems([]);void load();return()=>{sequence.current++;};},[load]);
  async function update(id:string,status:string){setUpdating(id);setError('');try{const response=await fetch(`/api/admin/inquiries/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await load();}catch(err){setError(err instanceof Error?err.message:'更新失敗，請重試。');}finally{setUpdating('');}}
  return <><div className="admin-toolbar"><p>全部 <strong>{counts.total}</strong> 筆 <span className="admin-pending">待聯繫 {counts.pending} 筆</span></p><div className="admin-filters"><div className="field"><label className="sr-only" htmlFor="status-filter">聯繫狀態</label><NativeSelect id="status-filter" value={filter} onChange={e=>setFilter(e.target.value)}><NativeSelectOption value="all">全部諮詢</NativeSelectOption><NativeSelectOption value="new">待聯繫</NativeSelectOption><NativeSelectOption value="contacted">已聯繫</NativeSelectOption></NativeSelect></div><Button variant="outline" onClick={()=>load()} disabled={loading}>重新整理</Button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading&&!items.length?<div className="inquiry-list" aria-label="正在讀取諮詢名單"><Skeleton className="h-40 w-full"/><Skeleton className="h-40 w-full"/></div>:!items.length&&!error?<p className="admin-message">{filter==='all'?'尚未收到諮詢。客人送出表單後，資料會出現在這裡。':'目前沒有符合此狀態的諮詢。'}</p>:<div className="inquiry-list">{items.map(item=>{const design=designs.find(d=>d.id===item.design);return <article className="inquiry-card" key={item.id}><div><h2>{item.name}</h2><p className="meta">{item.reference}</p><a href={`${item.contact_type==='email'?'mailto:':'tel:'}${encodeURIComponent(item.contact)}`}>{item.contact}</a><p className="meta">{new Date(item.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})}</p></div><dl><div><dt>需求</dt><dd>{services.find(s=>s.id===item.service)?.full||item.service}</dd></div><div><dt>預算</dt><dd>{budgets.find(b=>b.id===item.budget)?.label||item.budget}</dd></div>{design&&<div><dt>型號／款式</dt><dd>{design.model} · {design.name}</dd></div>}{item.material&&<div><dt>材質</dt><dd>{design?.options.find(o=>o.id===item.material)?.label||item.material}</dd></div>}{item.color&&<div><dt>顏色</dt><dd>{colors.find(c=>c.id===item.color)?.label||item.color}</dd></div>}{item.quote_amount!==null&&<div><dt>所選定價</dt><dd>{money(item.quote_amount)}</dd></div>}{item.watch_model&&<div><dt>手錶規格</dt><dd>{item.watch_model}</dd></div>}{item.notes&&<div><dt>補充</dt><dd>{item.notes}</dd></div>}</dl><div className="field"><label htmlFor={`status-${item.id}`}>聯繫狀態</label><NativeSelect id={`status-${item.id}`} value={item.status} disabled={updating===item.id} onChange={e=>update(item.id,e.target.value)}><NativeSelectOption value="new">待聯繫</NativeSelectOption><NativeSelectOption value="contacted">已聯繫</NativeSelectOption></NativeSelect>{updating===item.id&&<small role="status">正在更新…</small>}</div></article>;})}</div>}{more&&<Button className="more-button" variant="outline" disabled={loading} onClick={()=>load(items.length)}>{loading?'正在讀取…':'載入更多'}</Button>}</>;
}
